#!/bin/sh

cp -f $PWD/arch/arm/boot/zImage ~/androidcarz4.0.1/system/device/samsung/crespo/kernel

cp -f $PWD/drivers/net/wireless/bcm4329/bcm4329.ko ~/androidcarz4.0.1/system/device/samsung/crespo/bcm4329.ko

cp -f $PWD/drivers/scsi/scsi_wait_scan.ko ~/androidcarz4.0.1/system/device/samsung/crespo/scsi_wait_scan.ko
